language: objective-c

env:
 matrix:
  - MONO_VERSION="3.8.0"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
 - mozroots --import --sync

script:
 - mono .nuget/NuGet.exe restore TestNess.sln
 - xbuild 
 - .ci/nunit.sh TestNess.Lib.Test/bin/Debug/TestNess.Lib.Test.dll
